{% set name = "LCLSGeom" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LouConreux/LCLSGeom/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4105755ba2fb33e3f941862abfd11b0a273f299894d4db1ddc766c4ca0d48ef5

build:
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python 3.11.*
    - setuptools >=61.0
    - pip
  run:
    - python >=3.11,<3.12
    - numpy >=1.20.0
    - pyfai-base >=0.20.0

about:
  home: https://github.com/LouConreux/LCLSGeom
  license_file: LICENSE
  summary: "Miscellaneous functions for converting geometry files for LCLS geometry calibrations and optimizations."

extra:
  recipe-maintainers:
    - <your-github-handle>