{% set name = "psana" %}
{% set version = "4.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slac-lcls/lcls2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 21278bafa2f3366091bce5baf6a393ee95fccef5864091fcde53a43927634580

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - pkg-config
  host:
    - python
    - setuptools
    - pip
    - numpy =2
    - cython
    - rapidjson
    - meson
    - uv
    - ninja
    - prometheus-cpp
    - hatchling
  run:
    - python
    - numpy =2
    - matplotlib
    - requests
    - h5py
    - pyzmq
    - psmon
    - krtc
    - ipykernel 
    - prometheus_client
    - amityping
    - bson
    - kafka-python-ng
    - scipy
    - rapidjson
    - curl
    - bson
    - amityping
    - mypy_extensions
    - psmon
    - ipykernel
    - opencv
    - scikit-learn
    - pyabel
    - pyopencl
    - conda-forge::prometheus-cpp

about:
  home: https://github.com/slac-lcls/lcls2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'LCLS-II DAQ and Software'
  description: |
    DAQ and analysis software for LCLS-II
  doc_url: https://github.com/slac-lcls/lcls2 
  dev_url: https://github.com/slac-lcls/lcls2

extra:
  recipe-maintainers:
    - valmar
