{% set name = "psana" %}
{% set version = "4.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slac-lcls/lcls2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 72fc3b82e5ed013bc97501a3db8bc84cc094a7201a16bbadba94038bb22cf6f1

build:
  skip: True  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - pkg-config
  host:
    - python
    - setuptools
    - pip
    - numpy =2
    - cython
    - rapidjson
    - conda-forge::prometheus-cpp
  run:
    - python
    - numpy =2
    - matplotlib
    - requests
    - openmpi =5
    - mpi4py
    - h5py
    - pyzmq
    - psmon
    - krtc
    - ipykernel 
    - prometheus_client
    - amityping
    - bson
    - kafka-python-ng
    - scipy
    - rapidjson
    - curl
    - bson
    - amityping
    - mypy_extensions
    - psmon
    - ipykernel
    - opencv
    - scikit-learn
    - pyabel
    - pyopencl
    - prometheus-cpp

about:
  home: https://github.com/slac-lcls/lcls2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'LCLS-II DAQ and Software'
  description: |
    DAQ and analysis software for LCLS-II
  doc_url: https://github.com/slac-lcls/lcls2 
  dev_url: https://github.com/slac-lcls/lcls2

extra:
  recipe-maintainers:
    - valmar
